### ISSUE TITLE
NameError: name 'NoneType' is not defined

### ISSUE THREAD

**Issue by gauthamk28** [TorchStudio/torchstudio#1]
I downloaded the torchstudio(Windows 10) , choosed my anaconda pytorch environment , selected torchvision.datasets , MNIST and clicked on load , I am getting the following error 

NameError: name 'NoneType' is not defined

![image](https://user-images.githubusercontent.com/16622780/156171729-a8600624-4444-4c0a-b1f8-ae1bbfdc0b65.png)

**Comment by divideconcept** [comment]
Can you check the **Code** box at the top (next to MNIST, revealing the source code of MNIST) and copy the code shown here ?
