### ISSUE TITLE
M1 MacBook Pro -- Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.

### ISSUE THREAD

**Issue by TinkeringEngr** [TorchStudio/torchstudio#10]
Excited to try out this new tool!... but unable to get it working out of the box on a **2020 M1 MacBook Pro** using the latest version of **MacOS (Monterey 12.1)** following the recommended install instructions. 

The GUI loads fine, but upon **clicking the Load (⌘L) button** I get the following error (as it mentions its **Loading PyTorch..**) -- might just be a PyTorch issue as I haven't tried PyTorch standalone. 

`Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.
The processor must support the Intel(R) Supplemental Streaming SIMD Extensions 3 (Intel(R) SSSE3) instructions.
The processor must support the Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions.
The processor must support the Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.`

**Comment by divideconcept** [comment]
@TinkeringEngr I suppose you installed TorchStudio 0.9.1 or 0.9.2 ? This issue has been solved since TorchStudio 0.9.3: https://torchstudio.ai/download/

**Comment by divideconcept** [comment]
PS: delete the %USERPROFILE%/TorchStudio folder (Windows) or ~/TorchStudio folder (macOS/Ubuntu) before installing TorchStudio 0.9.4.

**Comment by TinkeringEngr** [comment]
I just used the MacOS installer from the TorchStudio website. I'll try the latest on Github. Thanks!

**Comment by divideconcept** [comment]
Ok - don't forget to fully delete the TorchStudio folder before reinstalling

**Comment by TinkeringEngr** [comment]
Ha never mind me -- I did install the older version 0.9.2, originally. I am now installing the latest 0.9.4. 

Since I have already taken some of your time, mind if I ask what packaging tools you are using? I am in the process of releasing my own open source project as a solo developer and it seems like you're a few steps ahead of me :)

**Comment by divideconcept** [comment]
If your question is about TorchStudio installers, I use:
-Inno Setup on Windows: https://jrsoftware.org/isinfo.php
-pkgbuild/productbuild on macOS
-dpkg-deb on Ubuntu
That being said, each require some scripting. I attached my installer generator scripts to this post if you want to have a look.
[torchstudio generateinstallers.zip](https://github.com/TorchStudio/torchstudio/files/8184312/torchstudio.generateinstallers.zip)

**Comment by TinkeringEngr** [comment]
Awesome, thank you.

Just finished installing TorchStudio_0.9.4, but came across a new issue. Packaging appears to go smoothly, but then it ends with the following screen. After clicking "OK" it takes me back to the install python environment. 

sudo rm -R ~/TorchStudio and Application moved to trash before install. 

<img width="274" alt="Screen Shot 2022-03-04 at 1 41 29 AM" src="https://user-images.githubusercontent.com/2432794/156729561-c2e8e610-08bf-43b4-9e59-8114f53ee532.png">
<img width="382" alt="Screen Shot 2022-03-04 at 1 42 05 AM" src="https://user-images.githubusercontent.com/2432794/156729580-929f2d79-167d-4abd-9554-d897a65d1bfc.png">

**Comment by divideconcept** [comment]
Yeah just noticed this, but just click "Install" again (no need to delete the TorchStudio folder this time) and it will be fine.

**Comment by TinkeringEngr** [comment]
I was hesitant to repeat myself with the install again, but it works as you said :) 

Excited to play with some tensors! Let me know if I can be of any help.

**Comment by divideconcept** [comment]
@TinkeringEngr I fixed this last step with TorchStudio 0.9.5: https://www.torchstudio.ai/download/
