### ISSUE TITLE
Download links of Torch Studio  seem to be broken

### ISSUE THREAD

**Issue by tatban** [TorchStudio/torchstudio#11]
As a PyTorch based Deep Learning researcher from Germany, I am excited to try out Torch Studio. However, the download links seem to be broken as they are landing on GitHub 404 page. Am I missing something? is Torch Studio not released for everyone so far?

**Comment by tatban** [comment]
Okay, so I closely observed the issue is, website is pointing to 0.9.3 where as the one you provided is 0.9.4 and hence is the issue. Probably the 0.9.3 is not public or so, maybe? 

This resolves:
https://github.com/TorchStudio/torchstudio/releases/download/0.9.4/TorchStudio_0.9.4-Windows_Installer.exe

This doesn't resolve:
https://github.com/TorchStudio/torchstudio/releases/download/0.9.4/TorchStudio_0.9.3-Windows_Installer.exe

**Comment by charleschiu2012** [comment]
> Btw, while installing from the link given by you, Windows Smart screen (for Windows 10) intercepts it raising some security concern, so maybe some certificates or so needs to be configured properly. I did not debug the issue though.

 - TorchStudio is made by @divideconcept. It's possible that there's no certificate from MicroSoft, and therefore raise the issue. It's really not a big deal as long as the program is open-source.
---



> Okay, so I closely observed the issue is, website is pointing to 0.9.3 where as the one you provided is 0.9.4 and hence is the issue. Probably the 0.9.3 is not public or so, maybe?
> 
> This resolves: https://github.com/TorchStudio/torchstudio/releases/download/0.9.4/TorchStudio_0.9.4-Windows_Installer.exe
> 
> This doesn't resolve: https://github.com/TorchStudio/torchstudio/releases/download/0.9.4/TorchStudio_0.9.3-Windows_Installer.exe

- Guess I have to leave this bug to the author himself. lol

**Comment by divideconcept** [comment]
Woops, thanks for pointing that out ! I need to automate that download link instead of manually changing it with each new version 😅
