### ISSUE TITLE
Note: Setup dialog checkbox for local GPU support can appear "backwards"

### ISSUE THREAD

**Issue by drscotthawley** [TorchStudio/torchstudio#13]
Hi! This seems wonderful. Thank you for sharing this. It's great and this is not a true issue, just a note that something might benefit from clarification in the setup/install menu: 

I have an NVIDIA RTX 2070 installed locally on my Pop!_OS (Ubuntu variant) 21.04 that works with...most things...,and when I installed TorchStudio I selected "Local NVIDIA GPU Support".   But I noticed that Training was set to "Local GPU" and no GPU option was available. When I went to Settings to try to select the GPU, there was no GPU option offered. 

...I figured out why:  

Turns out that the check-box for "Local NVIDIA GPU Support (6 GB)" in the setup popup dialogue box was ALREADY selected by default, but the checkbox appeared as a blank square, so I thought that meant it wasn't selected.  So then when I clicked the check-box (thinking I was selecting GPU support) it changed from a solid white square to a solid black square.   ...And apparently that means *NO* GPU support. 

...So I uninstalled and re-installed, this time leaving the dialog box to its default setting, and this time, it installed properly and used the GPU for training.  :-) 

Question/Suggestion: For later users, is there way to make it so that checkbox appears as being unchecked or checked, instead of just all white or all black?  Perhaps this is OS dependent; perhaps it looks "normal" on Windows/Mac/other Linux variants, and it's just something about my Ubuntu/Gnome setup that's weird.  If so, nevermind and close! ;-) 

P.S. - If another user finds this page because it seemed like your GPU wasn't being detected: Try uninstalling-and-reinstalling. :+1:

**Comment by divideconcept** [comment]
Ah, you're actually the second one mentioning the potential confusion !
To clarify this instead of a white square inside a black square I'm thinking of changing it to a white dot inside a black square - so it's more clear that the base is a black box, and that you fill it/activate it with a white dot. Makes sense to you ?

**Comment by drscotthawley** [comment]
Thanks for the reply!  Yes, that makes sense.  Feel free to close this at your leisure.

**Comment by divideconcept** [comment]
[TorchStudio 0.9.6](~/TorchStudio/) now shows more explicit checkbox !
