### ISSUE TITLE
Solving environment: ...working... 

### ISSUE THREAD

**Issue by drkp4** [TorchStudio/torchstudio#2]
Hi - Thank you for this amazing IDEa! Glad we found it. Having trouble setting up environment. Help is appreciated. Happy to provide more info.

**Process**
Downloaded **TorchStudio_0.92-Mac_Installer.pkg**
Installed Successfully
Opened TorchStudio
TorchStudio Python Environment popup
Clicked **Install (recommended)**
**Stuck in Solving environment: ...working...**

**System Information**
macOS Monterey
Version 12.2.1
MacBook Pro (13-inch, M1, 2020)
Chip Apple M1
Memory 16 GB

**TorchStudio Python Environment Installation**
Downloading, installing and setting up a Python environment for TorchStudio.
This may take up to 5 minutes depending on your download speed, and up to 6GB.

Downloading Python installer (Miniconda3)...
Download complete: /Users/drkp4/TorchStudio/python-miniconda3.sh

Installing Python in /Users/drkp4/TorchStudio/python...
Installation complete.

Downloading and installing PyTorch and additional packages:
nomkl pytorch torchvision torchaudio datasets scipy pandas matplotlib-base python-graphviz paramiko

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working...

**Comment by divideconcept** [comment]
It's not necessarily stuck. On some computers/systems, that "Solving environment" step might take some time.
Let me know if it's still stuck after waiting 10 minutes.
If it's still stuck, you can install the requirements manually:
In macOS open a terminal (**Launchpad > Other > Terminal**), and type the following line:
`~/TorchStudio/python/condabin/conda install nomkl pytorch torchvision torchaudio datasets scipy pandas matplotlib-base python-graphviz paramiko -c pytorch -c nvidia -c huggingface -c conda-forge -c anaconda`

**Comment by drkp4** [comment]
Thank you! It does seem stuck (more than an hour of waiting)

Tried the following. Should I try a re-install? Thanks so much!

**Attempting to Run Conda from Finder**
drkp4@drkp4s-MacBook-Pro ~ % /Users/drkp4/TorchStudio/python/condabin/conda ; exit;
zsh: /Users/drkp4/TorchStudio/python/condabin/conda: bad interpreter: /Users/drkp4/TorchStudio/python.tmp/bin/python: no such file or directory

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Terminal Suggested Solution**
drkp4@drkp4s-MacBook-Pro condabin % ~/TorchStudio/python/condabin/conda install nomkl pytorch torchvision torchaudio datasets scipy pandas matplotlib-base python-graphviz paramiko -c pytorch -c nvidia -c huggingface -c conda-forge -c anaconda
zsh: /Users/drkp4/TorchStudio/python/condabin/conda: bad interpreter: /Users/drkp4/TorchStudio/python.tmp/bin/python: no such file or directory
drkp4@drkp4s-MacBook-Pro condabin % 

**Terminal Exploration**
drkp4@drkp4s-MacBook-Pro python % ls
LICENSE.txt	condabin	include		python.app	ssl
bin		envs		lib		share
conda-meta	etc		pkgs		shell
drkp4@drkp4s-MacBook-Pro python % cd condabin 
drkp4@drkp4s-MacBook-Pro condabin % ls
conda
drkp4@drkp4s-MacBook-Pro condabin % cd conda 
cd: not a directory: conda
drkp4@drkp4s-MacBook-Pro condabin % ls
conda
drkp4@drkp4s-MacBook-Pro condabin % conda install nomkl pytorch torchvision torchaudio datasets scipy pandas matplotlib-base python-graphviz paramiko -c pytorch -c nvidia -c huggingface -c conda-forge -c anaconda
zsh: command not found: conda
drkp4@drkp4s-MacBook-Pro condabin % conda --help
zsh: command not found: conda

**Comment by sodoherty-ai** [comment]
Same issue: 

Model Name:	MacBook Pro
Model Identifier:	MacBookPro18,2
Chip:	Apple M1 Max
Total Number of Cores:	10 (8 performance and 2 efficiency)
Memory:	64 GB

Suggested command line option fails:

`/Users/xxx/TorchStudio/python/condabin/conda: bad interpreter: /Users/xxx/TorchStudio/python.tmp/bin/python: no such file or directory`

**Comment by sodoherty-ai** [comment]
For the M1 I had recompile pytorch on the machine using this (in pycharm pro). 

    conda install -c conda-forge pytorch

When I try to use that environment Torch Studio throws the error: 

    pytorch 1.10 required. 1.09 installed.

**Comment by divideconcept** [comment]
I can repro the issue on my M1 laptop. Investigating...

**Comment by drkp4** [comment]
would love to help - happy to connect on discord/slack and troubleshoot live

**Comment by divideconcept** [comment]
To give you some insights, there was a very recent update (3 days ago ?) of the MKL package whose PyTorch depends on. Unfortunately, that latest MKL update is not compatible with M1 machines at all. As a workaround, I added the "nomkl" package during TorchStudio initialisation, which somehow block the use of MKL (but doesn't stop PyTorch from working).
Unfortunately, it now seems that combining nomkl and pytorch during install is blocking conda during initialisation...
I'm now trying different combinations to see what works/what doesn't.

**Comment by divideconcept** [comment]
related: https://stackoverflow.com/questions/70830755/intel-mkl-fatal-error-this-system-does-not-meet-the-minimum-requirements-for-us/71190634

**Comment by drkp4** [comment]
normal Mac situation! haha.

will try on linux and revert

**Comment by arnavdas88** [comment]
I faced the same issue with my i5 Mac. @drkp4 This is what solved my issue :

1.) First, conda needs `python.tmp` directory for some reason instead of `python` so I created a symbolic link. 
```shell
$ cd ~/TorchStudio/
$ ln -s ./python ./python.tmp
```
Now that `./python.tmp` exists, we can use `conda --help` and other operations... 

2.) Add the channel "conda-forge" and update.
```shell
$ cd ~/TorchStudio/python/condabin/

$ ./conda config --add channels conda-forge
$ ./conda update conda
```

3.) Once that is done, I was able to successfully run the command  provided by @divideconcept 
```shell
$ ~/TorchStudio/python/condabin/conda install nomkl pytorch torchvision torchaudio datasets scipy pandas matplotlib-base python-graphviz paramiko -c pytorch -c nvidia -c huggingface -c conda-forge -c anaconda
```


---


Although it did give me a small warning in the end, I was able to successfully run TorchStudio after that
The WARNING : 
```
| WARNING conda.core.envs_manager:register_env(50): Unable to register environment. Path not writable or missing.
  environment location: /Users/andrew/TorchStudio/python.tmp
  registry file: /Users/andrew/.conda/environments.txt
```

**Comment by divideconcept** [comment]
Ok, after testing A LOT of different combinations, I found that the most reliable for mac was to specify explicitly the PyTorch version to install, in this case the version right before the latest update (PyTorch 1.10.1 instead of 1.10.2, because 1.10.2 introduce a dependency on a newer MKL incompatible with M1 macs).

Now building new installers, TorchStudio 0.9.3 should be available in the next hour or so.

**Comment by divideconcept** [comment]
The new release is available ! TorchStudio 0.9.3 -> https://torchstudio.ai/download/
Please delete completely your ~/TorchStudio folder before installing and running this one.

**Comment by sodoherty-ai** [comment]
Just confirming. It installs perfectly now.

**Comment by drkp4** [comment]
winner winner chicken dinner! hope to find ways to help the project! thank you so much :)
