### ISSUE TITLE
Missing MSVCP140.dll Install Errors

### ISSUE THREAD

**Issue by alexhiggins732** [TorchStudio/torchstudio#20]
Then running the installer on Windows 10 results in complaints about several missing MSVCP140.dlls when attempting to launch the application after the installer completes.

![image](https://user-images.githubusercontent.com/2246388/157369783-a973d2c3-21f8-4b0c-9fd3-b7a4f94e8579.png)
![image](https://user-images.githubusercontent.com/2246388/157369822-9f8e3235-daf9-4e9c-8e55-666209e986ab.png)

![image](https://user-images.githubusercontent.com/2246388/157368661-ba7f83d7-5370-40c1-97e8-012ee01cb70a.png)
![image](https://user-images.githubusercontent.com/2246388/157368778-7d99953b-46aa-4577-91dc-9144cc8ac01b.png)
![image](https://user-images.githubusercontent.com/2246388/157368822-9f787b9c-3a98-4702-8ecf-96a976866bce.png)
![image](https://user-images.githubusercontent.com/2246388/157368864-a6111eaa-d5be-40d3-a657-bcd90792122a.png)

![image](https://user-images.githubusercontent.com/2246388/157369451-58716f13-ebfa-41e8-aafc-5a361ae88420.png)

I have attempted to install the [Visual C++ Redistributable for Visual Studio 2015 ] which should contain the v14 dlls.
(https://www.microsoft.com/en-us/download/details.aspx?id=481

**Comment by alexhiggins732** [comment]
I was able to resolve the issue by installing the [Microsoft Visual C++ Redistributable packages for Visual Studio 2015, 2017, 2019, and 2022](https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170).

<html>
<body>


Architecture | Link | Notes
-- | -- | --
ARM64 | https://aka.ms/vs/17/release/vc_redist.arm64.exe | Permalink for latest supported ARM64 version
X86 | https://aka.ms/vs/17/release/vc_redist.x86.exe | Permalink for latest supported x86 version
X64 | https://aka.ms/vs/17/release/vc_redist.x64.exe | Permalink for latest supported x64 version. The X64 redistributable package contains both ARM64 and X64 binaries. This package makes it easy to install required Visual C++ ARM64 binaries when the X64 redistributable is installed on an ARM64 device.


</body>
</html>

**Comment by divideconcept** [comment]
Fixed with [TorchStudio 0.9.7](https://github.com/TorchStudio/torchstudio/releases/tag/0.9.7)
