### ISSUE TITLE
Windows Smart Screen Error

### ISSUE THREAD

**Issue by alexhiggins732** [TorchStudio/torchstudio#21]
Windows smart screen blocks the installer download from both https://torchstudio.ai/ and the git hubs release page.
![image](https://user-images.githubusercontent.com/2246388/157368361-4beb6f04-d97e-484c-8b3b-3026f8431a8b.png)

Further warning after clicking keep:
![image](https://user-images.githubusercontent.com/2246388/157368487-8618f5f5-d337-41e5-a52b-53319ba351b0.png)

![image](https://user-images.githubusercontent.com/2246388/157371815-db04ffa1-4d28-42f7-aa4b-32386de47122.png)

**Comment by divideconcept** [comment]
This happen unfortunately with every freshly released installer, as TorchStudio use an OV Certificate, until it's downloaded by enough people so that MS/Windows can trust it.
