### ISSUE TITLE
MultiLabel and ValuesDistribution Analyzers Throw Exception On Windows

### ISSUE THREAD

**Issue by alexhiggins732** [TorchStudio/torchstudio#24]
Multiple attempts to run `MultiLabel` and `ValuesDistribution` analzyers throw exceptions on various models including the `Random` and `MNIST` models.

```
datasetanalyze: "File \\TorchStudio\\python\\lib\\site-packages\\torch\\__init__.py, line 124, in <module>
raise err
OSError: 22
```

Error: `MultiLabel` on the `Random` model
![image](https://user-images.githubusercontent.com/2246388/157375688-4ad02462-6f83-404e-b27f-db7536081d7d.png)

Error: `ValuesDistribution` on the `Random` model
![image](https://user-images.githubusercontent.com/2246388/157375731-7e09b3ac-d1f3-4813-91d1-6ada11991e53.png)

Error: `ValuesDistribution` on the `MNIST` model
![image](https://user-images.githubusercontent.com/2246388/157376244-3ed0086b-7522-4e62-8cc1-808a87725187.png)

`Multiclass` analyzer runs without issue.
![image](https://user-images.githubusercontent.com/2246388/157375702-d5d5e521-c969-4698-be1b-bffebe7bba95.png)

Log Excerpt:

> 
> 23:52:55.849 INFO  starting TorchStudio 0.9.6 on "Windows 10 Version 2004"
> 23:52:58.098 INFO  python check: "Checking Python version...\n\nChecking required packages...\n\nLoading PyTorch...\n\nListing devices...\n\n" "Functional environment (Python 3.9, PyTorch 1.10, Devices: CPU (cpu))\n"
> 23:52:59.162 INFO  checking notifications...
> 23:52:59.364 INFO  inference: "Loading PyTorch...\n\n" ""
> 
> ...
> 
> 23:55:04.677 INFO  datasetload: "Loading PyTorch...\n\n" ""
> 23:55:06.473 INFO  datasetload: "Dataset script connected\n\n" ""
> 23:55:06.473 INFO  datasetload: "Loading dataset...\n\n" ""
> 23:55:06.848 INFO  datasetload: "" "Loading complete\n"
> 23:55:08.755 WARNING  QProcess: Destroyed while process ("C:\\Users\\WDAGUtilityAccount\\TorchStudio\\python\\python") is still running.
> 23:55:08.786 INFO  datasetanalyze end: "" ""
> 23:55:08.786 INFO  datasetanalyze disconnected
> 23:55:08.786 WARNING  QCoreApplication::postEvent: Unexpected null receiver
> 23:55:09.817 INFO  datasetanalyze: "Analyze script connected\n\n" ""
> 23:55:09.817 INFO  datasetanalyze: "Setting analyzer code...\n\n" ""
> 23:55:10.989 INFO  datasetanalyze: "Analyzing...\n\n" ""
> 23:55:11.005 INFO  datasetload: "Connecting to analyzer...\n\n" ""
> 23:55:11.005 INFO  datasetload: "\rSending samples to analyzer...:   0%|          | ? left\n\n" ""
> 23:55:11.005 INFO  datasetanalyze: "\rAnalyzing...:   0%|          | ? left\n\n" ""
> 23:55:11.114 INFO  datasetload: "\rSending samples to analyzer...:   1%|          | 00:19 left\n\n" ""
> 23:55:11.114 INFO  datasetanalyze: "\rAnalyzing...:   1%|          | 00:19 left\n\n" ""
> 23:55:11.223 INFO  datasetload: "\rSending samples to analyzer...:   1%|          | 00:18 left\n\n" ""
> 23:55:11.223 INFO  datasetanalyze: "\rAnalyzing...:   1%|          | 00:18 left\n\n" ""
> 23:55:11.333 INFO  datasetload: "\rSending samples to analyzer...:   2%|\xE2\x96\x8F         | 00:15 left\n\n" ""
> 23:55:11.333 INFO  datasetanalyze: "\rAnalyzing...:   2%|\xE2\x96\x8F         | 00:15 left\n\n" ""
> 23:55:11.442 INFO  datasetanalyze: "\rAnalyzing...:   3%|\xE2\x96\x8E         | 00:14 left\n\n" ""
> 23:55:11.442 INFO  datasetload: "\rSending samples to analyzer...:   3%|\xE2\x96\x8E         | 00:14 left\n\n" ""
> 23:55:11.551 INFO  datasetanalyze: "\rAnalyzing...:   4%|\xE2\x96\x8E         | 00:13 left\n\n" ""
> 23:55:11.551 INFO  datasetload: "\rSending samples to analyzer...:   4%|\xE2\x96\x8E         | 00:13 left\n\n" ""
> 23:55:11.661 INFO  datasetanalyze: "\rAnalyzing...:   4%|\xE2\x96\x8D         | 00:13 left\n\n" ""
> 23:55:11.661 INFO  datasetload: "\rSending samples to analyzer...:   4%|\xE2\x96\x8D         | 00:13 left\n\n" ""
> 
> ...
> 
> 23:55:23.473 INFO  datasetload: "\rSending samples to analyzer...:  98%|\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x8A| 00:00 left\n\n" ""
> 23:55:23.583 INFO  datasetload: "\rSending samples to analyzer...:  99%|\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x89| 00:00 left\n\n" ""
> 23:55:23.583 INFO  datasetanalyze: "\rAnalyzing...:  99%|\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x89| 00:00 left\n\n" ""
> 23:55:23.661 INFO  datasetload: "\rSending samples to analyzer...: 100%|\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88| 00:00 left\n\n\n" ""
> 23:55:23.661 INFO  datasetanalyze: "\rAnalyzing...: 100%|\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88\xE2\x96\x88| 00:00 left\n\n\n" ""
> 23:55:23.755 INFO  datasetload: "" "Samples transfer to analyzer completed\n"
> 23:55:23.755 INFO  datasetanalyze: "" "Analysis complete\n"
> 23:55:26.380 WARNING  QProcess: Destroyed while process ("C:\\Users\\WDAGUtilityAccount\\TorchStudio\\python\\python") is still running.
> 23:55:26.380 INFO  datasetanalyze end: "" ""
> 23:55:26.380 INFO  datasetanalyze disconnected
> 23:55:26.380 WARNING  QCoreApplication::postEvent: Unexpected null receiver
> 23:55:26.723 INFO  datasetanalyze: "Analyze script connected\n\n" ""
> 23:55:26.723 INFO  datasetanalyze: "Setting analyzer code...\n\n" ""
> 23:55:26.895 INFO  datasetanalyze: "File C:\\Users\\WDAGUtilityAccount\\TorchStudio\\python\\lib\\site-packages\\torch\\__init__.py, line 124, in <module>\nraise err\nOSError: 22\n" ""
>

**Comment by divideconcept** [comment]
Fixed in [TorchStudio 0.9.7](https://github.com/TorchStudio/torchstudio/releases/tag/0.9.7)
