### ISSUE TITLE
How is this packaged?

### ISSUE THREAD

**Issue by netroy** [TorchStudio/torchstudio#25]
Hi,

Is there any documentation on how the distributed versions of torchstudio are packaged?
I see that the `deb` file contains a single binary and lots of Qt libraries. but, its unclear how these files get created.
This makes the package look a bit suspicious.

Another advantage of documentation on packaging would be that we (the community) can help package this in more modern formats than deb (like Flatpak and Appimage), and get the app working on almost all modern Linux distros. 

Thanks for your hard work,
:slightly_smiling_face:

**Comment by divideconcept** [comment]
Hi, TorchStudio is composed of 2 components: a C++ GUI, and open source python scripts (cf the architecture drawing in the [README.md](https://github.com/TorchStudio/torchstudio/blob/main/README.md)). This repo contains the open source python scripts, and the [official releases](https://github.com/TorchStudio/torchstudio/releases) contains installers which deploy the compiled GUI binaries (in the appropriate application folder depending on your OS) and its the corresponding python scripts (in ~/TorchStudio/torchstudio).
I hope to clarify a bit the status, contributions, etc later this week.
Thanks for offering to help with Linux packaging, I'm indeed a bit new to this and went for the most known distribution.

**Comment by Jdreioe** [comment]
I'd love to see a Flatpak format as well, since .deb only works on Ubuntu. Fedora, Arch, OpenSuse cannot install TorchStudio via conversion via the "alien" package.

**Comment by divideconcept** [comment]
Is that Flatpak really standard ? I'm not that much familiar with the Linux world, but it looks like you need to install Flatpak first before being able to install a Flatpakaged software ?

**Comment by Jdreioe** [comment]
> Is that Flatpak really standard ? I'm not that much familiar with the Linux world, but it looks like you need to install Flatpak first before being able to install a Flatpakaged software ?

Flatpak is able to be installed on most (if not all) Linux distributions. It's something that takes one command to install for most distributions (except for Gentoo, where it's two commands) if not already installed by default. Also, Flatpaks can be used on ChromeOS, Steam Deck, etc.

**Comment by divideconcept** [comment]
Turns out (based on the reddit comments) that flatpak is not well suited for the way TorchStudio is built.
However starting with TorchStudio 0.9.8 a RPM installer is now also provided, which with the DEB installer should cover most Linux distributions !
