### ISSUE TITLE
Load scikit-learn models

### ISSUE THREAD

**Issue by Mirodil** [TorchStudio/torchstudio#28]
Hello,

Thank you for this awesome software. Is it possible to use scikit-learn models instead off pytorch?

Thank you an advance

**Comment by divideconcept** [comment]
Hi, thanks !
Scikit-learn models aren't compatible with PyTorch, AFAIK.

**Comment by Mirodil** [comment]
Yes, I know it is PyTorch tool, and it is awesome tool. I was just wondering how it can be adopted to Scikit-learn.
