### ISSUE TITLE
Ubuntu support version

### ISSUE THREAD

**Issue by yongen9696** [TorchStudio/torchstudio#31]
Does version torchstudio 0.9.7 only supports Ubuntu 20.04 and higher?

**Comment by divideconcept** [comment]
It support other Linux distributions, but regarding Ubuntu only 20.04 and higher is supported yes.

**Comment by yongen9696** [comment]
I see, was trying to run on an older version of Ubuntu, 18.04.

Thanks for your reply, will close the issue now.
