### ISSUE TITLE
Build model graph

### ISSUE THREAD

**Issue by jplasser** [TorchStudio/torchstudio#32]
Hi,
not an issue, but a question: How's the graph built, any references I can use, if I want build such a Graph myself?

Thank you!

**Comment by divideconcept** [comment]
Hi, the model is parsed and explored with torch.fx, see https://github.com/TorchStudio/torchstudio/blob/main/torchstudio/modelbuild.py
The parsed data is then rendered to a svg using graphviz, see
https://github.com/TorchStudio/torchstudio/blob/main/torchstudio/graphdraw.py

**Comment by jplasser** [comment]
Thank you for the details!
