### ISSUE TITLE
Stuck installation

### ISSUE THREAD

**Issue by Captain-Yellow** [TorchStudio/torchstudio#33]
Hi 
I am on m1 macbook pro and I try to install Torch Studio but it gets stuck every time
I just click on "install (recommended)" and wait for hours but nothing happened
And the log file has the same text.
<img width="1097" alt="Screen Shot 2022-04-18 at 21 19 28" src="https://user-images.githubusercontent.com/50849702/163843408-cf561826-9eb8-4b25-b5aa-e70b2595c4e2.png">

**Comment by wzh1994** [comment]
me too

**Comment by wzh1994** [comment]
My guess is that conda is stuck in an infinite loop when parsing package dependencies.  I solved the problem by installing in groups:
cd ~/TorchStudio/python/bin/conda
./conda install nomkl pytorch torchvision torchaudio -c pytorch -c conda-forge -c anaconda
./conda install datasets scipy pandas -c pytorch -c conda-forge -c anaconda
./conda install matplotlib-base python-graphviz paramiko -c pytorch -c conda-forge -c anaconda

**Comment by divideconcept** [comment]
@wzh1994 thanks for the tip. Not sure why conda got stuck though.
NB: note that on mac, due to MKL being incompatible with M1 CPUs, I had to specify a specific version of torch and mkl (as seen in the screenshot).

**Comment by Captain-Yellow** [comment]
@wzh1994 Thank you very much
Your solution solved my problem 🙏🌸🌺
