### ISSUE TITLE
Would you please consider providing another way to use TorchStudio like TensorBoard or Kite?

### ISSUE THREAD

**Issue by songyuc** [TorchStudio/torchstudio#34]
Hi, guys,
I am wondering whether you would consider providing another way to use TorchStudio like Tensorboard or Kite;
I mean, maybe there could be some python APIs that we could call so as to present the results in the TorchStudio, in which way, we could write codes in PyCharm and use TorchStudio like TensorBoard.

Thanks sincerely for the wonderful features of TorchStudio!

Looking forward to your reply.

**Comment by divideconcept** [comment]
Considering it the other way, what features from TensorBoard and PyCharm would you like to see in TorchStudio ?

**Comment by songyuc** [comment]
Hi @divideconcept ! Please give me some time to organize my thoughts.
