### ISSUE TITLE
Font and color theme modification required

### ISSUE THREAD

**Issue by JiantingFeng** [TorchStudio/torchstudio#37]
Thank you for such an awesome project, but I don't know if I can change the font size and color theme? Cuz I have a high resolution screen and the text in TorchStudio is extremely small. :(

**Comment by divideconcept** [comment]
What area of the software in particular ? The model description on the left side ? Unfortunately the text size can't be changed in that area right now, but will be in the next update. FYI when you display the source code of a model, it can be sized by holding down the CTRL key + mouse wheel. The same will be implemented for the description soon.
Regarding the other areas of the software, it doesn't seem too small to me. Feel free to provide a screenshot to illustrate what you mean.
