### ISSUE TITLE
RuntimeError: Currently, AutocastCPU only support Bfloat16 as the autocast_cpu_dtype

### ISSUE THREAD

**Issue by lbgitjp** [TorchStudio/torchstudio#41]
I followed the steps from here: https://www.torchstudio.ai/getstarted/,

But at the last step shows a error .

**torch.set_autocast_cpu_dtype(self.fast_dtype)  # type: ignore[arg-type]
RuntimeError: Currently, AutocastCPU only support Bfloat16 as the autocast_cpu_dtype**

please see below pic:
![1](https://user-images.githubusercontent.com/43297325/194864898-ac7d0d1a-b784-4723-bc66-8fd051db7339.png)

log file:
[TorchStudio 2022.10.10-20.09.33.txt](https://github.com/TorchStudio/torchstudio/files/9745988/TorchStudio.2022.10.10-20.09.33.txt)

please tell me how to resolve it?

thanks!

**Comment by divideconcept** [comment]
This is now fixed with 0.9.12: https://github.com/TorchStudio/torchstudio/releases/tag/0.9.12

**Comment by lbgitjp** [comment]
It works, thank you!
