### ISSUE TITLE
Can I just install the GUI without adding torch to my local environment?

### ISSUE THREAD

**Issue by agungshiro** [TorchStudio/torchstudio#48]
I just want to connect and work with my remote server, and I don't want to install the whole pytorch to my local computer due to the space (size) issue. Can I just install the GUI without adding pytorch to my local environment?
Thank you

**Comment by divideconcept** [comment]
You'll still need to install PyTorch locally to build models and other tasks for instance.
I suggest you either install PyTorch without CUDA (5GB instead of 16GB) or select an already existing PyTorch environment on your computer.

**Comment by agungshiro** [comment]
Ok. Thanks for your answer
