### ISSUE TITLE
Can't install/open TorchStudio

### ISSUE THREAD

**Issue by ssuezer** [TorchStudio/torchstudio#54]
Hey,

I tried to install the TorchStudio version 0.9.15 and 0.9.14 but for both versions it gives me the same error message like there: [https://github.com/TorchStudio/torchstudio/issues/53](https://github.com/TorchStudio/torchstudio/issues/53) .
Now I successfully installed the TorchStudio version 0.9.13 and as mentioned here [https://stackoverflow.com/questions/75571036/torchstudio-cannot-run](https://stackoverflow.com/questions/75571036/torchstudio-cannot-run) I have to open the "python.exe" in this path "C:\Users\sedat\TorchStudio\python" to start TorchStudio but all it does is opening this terminal window
![image](https://github.com/TorchStudio/torchstudio/assets/133764959/7eb338e2-12c3-474a-a954-ca2e6aa672b0)

 
Does anyone know what I can do now?

**Comment by divideconcept** [comment]
Issue solved with 0.9.16: https://github.com/TorchStudio/torchstudio/releases/tag/0.9.16
Make sure to delete ~/TorchStudio before running 0.9.16
