### ISSUE TITLE
NameError: name 'Any' is not defined

### ISSUE THREAD

**Issue by tvanachteren** [TorchStudio/torchstudio#55]
![image](https://github.com/TorchStudio/torchstudio/assets/55275355/aab02712-9b3a-4e6b-a36f-8c98e142ed35)

On Windows, when trying to build the mobilenet_v2 model with weights 'IMAGENET1K_V2' following the tutorial on "Transfer Learning", I get the error: NameError: name 'Any' is not defined.
The MobileNetV2 without pretrained weights worked fine.

**Comment by Armin234** [comment]
I have the same problem, any solution ?

**Comment by philippejuhel** [comment]
Hi, 

Same for me. 
TorchStudio version is : 0.9.16 on Ubuntu 22.04.
I try with other pretrained networks and got the same error.

Philippe

**Comment by philippejuhel** [comment]
After hours of debugging, I manage to correct this problem. (let me know if the explanation is OK)

When you select a pretrained model, it uses a description from torchvision website (for example : [mobilenet_v2](https://pytorch.org/vision/main/_modules/torchvision/models/mobilenetv2.html#mobilenet_v2)) 
In this declaration, it's written : `**kwargs: Any ` (the famous not defined 'Any')
So, before clicking on the **Build** button, check the **Code** checkbox to access the `def mobilenet_v2` code and replace 
`**kwargs: Any`
by 
`**kwargs: None`

and now, the model is built.


Philippe

**Comment by divideconcept** [comment]
This should now be fixed with TorchStudio 0.9.17: https://github.com/TorchStudio/torchstudio/releases/tag/0.9.17
