### ISSUE TITLE
Remote environment not possible

### ISSUE THREAD

**Issue by DarkSky7** [TorchStudio/torchstudio#59]
https://www.torchstudio.ai/remoteservers/ suggests the possibility of running torch on a network server, but the dialog "TorchStudio Python Environment" doesn't allow for that possibility.  It assumes that the local machine is providing python and it wants 'PyTorch' or 'PyTorch with CUDA' selected.  I'm running on a Windows-10 machine (where tensorflow always lags its availability on Linux); TensorFlow is built from source to run on the CPU with optimizations: --copt=-march=native --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-msse4.2 on a nearby Fedora-38 machine; the last four build options are redundant with the first, but were included in the bazel build just in case.  I don't mind storing python sources locally, but the execution environment has to be that Fedora-38 machine.  When network execution supports my run-time configuration, I can begin using TorchStudio; until then it's not an option.

**Comment by divideconcept** [comment]
@DarkSky7 this should now be fixed in 0.9.17: https://github.com/TorchStudio/torchstudio/releases/tag/0.9.17
