### ISSUE TITLE
torchstudio install error  (OS windows11)

### ISSUE THREAD

**Issue by Gilkovitch** [TorchStudio/torchstudio#60]
Downloading, installing and setting up a windows python environment
This may take up to 16 minutes depending on your download speed, and up to 16 GB.

Downloading Python installer Miniconda3-latest-Windows-x86_64.exe...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 78.1M  100 78.1M    0     0  45.7M      0  0:00:01  0:00:01 --:--:-- 45.7M

Installing Python in C:\Users\tasha\TorchStudio\python...
Downloading and installing the graphviz package...

Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\tasha\TorchStudio\python

  added / updated specs:
    - python-graphviz

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2024.2.2   |       h56e8100_0         152 KB  conda-forge
    cairo-1.16.0               |    hd694305_1014         2.3 MB  conda-forge
    certifi-2024.2.2           |     pyhd8ed1ab_0         157 KB  conda-forge
    conda-24.1.2               |  py312h2e8e312_0         1.2 MB  conda-forge
    font-ttf-dejavu-sans-mono-2.37|       hab24e00_0         388 KB  conda-forge
    font-ttf-inconsolata-3.000 |       h77eed37_0          94 KB  conda-forge
    font-ttf-source-code-pro-2.038|       h77eed37_0         684 KB  conda-forge
    font-ttf-ubuntu-0.83       |       h77eed37_1         1.5 MB  conda-forge
    fontconfig-2.14.0          |       hce3cb01_0         201 KB  conda-forge
    fonts-conda-ecosystem-1    |                0           4 KB  conda-forge
    fonts-conda-forge-1        |                0           4 KB  conda-forge
    freetype-2.12.1            |       hdaf720e_2         498 KB  conda-forge
    fribidi-1.0.10             |       h8d14728_0          63 KB  conda-forge
    getopt-win32-0.1           |       hcfcfb64_1          21 KB  conda-forge
    gettext-0.19.8.1           |    ha2e2712_1008         4.9 MB  conda-forge
    graphite2-1.3.13           |             1000          97 KB  conda-forge
    graphviz-6.0.1             |       h8f5d4a1_0         1.4 MB  conda-forge
    gts-0.7.6                  |       h7c369d9_2         188 KB  conda-forge
    harfbuzz-5.2.0             |       h27de254_0         1.0 MB  conda-forge
    icu-70.1                   |       h0e60522_0        17.0 MB  conda-forge
    jpeg-9e                    |       hcfcfb64_3         283 KB  conda-forge
    lerc-4.0.0                 |       h63175ca_0         190 KB  conda-forge
    libdeflate-1.14            |       hcfcfb64_0          73 KB  conda-forge
    libexpat-2.5.0             |       h63175ca_1         135 KB  conda-forge
    libgd-2.3.3                |       h891f43f_3         459 KB  conda-forge
    libglib-2.72.1             |       h3be07f2_0         3.1 MB  conda-forge
    libpng-1.6.43              |       h19919ed_0         339 KB  conda-forge
    libsqlite-3.45.1           |       hcfcfb64_0         850 KB  conda-forge
    libtiff-4.4.0              |       hc4f729c_5         787 KB  conda-forge
    libwebp-1.3.2              |       hcfcfb64_1          69 KB  conda-forge
    libwebp-base-1.3.2         |       hcfcfb64_0         263 KB  conda-forge
    libxcb-1.15                |       hcd874cb_0         947 KB  conda-forge
    libzlib-1.2.13             |       hcfcfb64_5          54 KB  conda-forge
    m2w64-gcc-libgfortran-5.3.0|                6         342 KB  conda-forge
    m2w64-gcc-libs-5.3.0       |                7         520 KB  conda-forge
    m2w64-gcc-libs-core-5.3.0  |                7         214 KB  conda-forge
    m2w64-gmp-6.1.0            |                2         726 KB  conda-forge
    m2w64-libwinpthread-git-5.0.0.4634.697f757|                2          31 KB  conda-forge
    msys2-conda-epoch-20160418 |                1           3 KB  conda-forge
    openssl-3.2.1              |       hcfcfb64_0         7.8 MB  conda-forge
    pango-1.50.10              |       hc1549de_0         476 KB  conda-forge
    pcre-8.45                  |       h0e60522_0         518 KB  conda-forge
    pixman-0.43.4              |       h63175ca_0         451 KB  conda-forge
    pthread-stubs-0.4          |    hcd874cb_1001           6 KB  conda-forge
    python-3.12.2              |h2628c8c_0_cpython        15.3 MB  conda-forge
    python-graphviz-0.20.1     |     pyh22cad53_0          35 KB  conda-forge
    python_abi-3.12            |          4_cp312           7 KB  conda-forge
    tk-8.6.13                  |       h5226925_1         3.3 MB  conda-forge
    ucrt-10.0.22621.0          |       h57928b3_0         1.2 MB  conda-forge
    vc14_runtime-14.38.33130   |      h82b7239_18         732 KB  conda-forge
    vs2015_runtime-14.38.33130 |      hcb4865c_18          17 KB  conda-forge
    xorg-kbproto-1.0.7         |    hcd874cb_1002          28 KB  conda-forge
    xorg-libice-1.1.1          |       hcd874cb_0         154 KB  conda-forge
    xorg-libsm-1.2.4           |       hcd874cb_0          84 KB  conda-forge
    xorg-libx11-1.8.7          |       hefa74cf_0         797 KB  conda-forge
    xorg-libxau-1.0.11         |       hcd874cb_0          50 KB  conda-forge
    xorg-libxdmcp-1.1.3        |       hcd874cb_0          66 KB  conda-forge
    xorg-libxext-1.3.4         |       hcd874cb_2         217 KB  conda-forge
    xorg-libxpm-3.5.17         |       hcd874cb_0         191 KB  conda-forge
    xorg-libxt-1.3.0           |       hcd874cb_1         656 KB  conda-forge
    xorg-xextproto-7.3.0       |    hcd874cb_1003          30 KB  conda-forge
    xorg-xproto-7.0.31         |    hcd874cb_1007          74 KB  conda-forge
    zlib-1.2.13                |       hcfcfb64_5         105 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        73.5 MB

The following NEW packages will be INSTALLED:

  cairo              conda-forge/win-64::cairo-1.16.0-hd694305_1014 
  font-ttf-dejavu-s~ conda-forge/noarch::font-ttf-dejavu-sans-mono-2.37-hab24e00_0 
  font-ttf-inconsol~ conda-forge/noarch::font-ttf-inconsolata-3.000-h77eed37_0 
  font-ttf-source-c~ conda-forge/noarch::font-ttf-source-code-pro-2.038-h77eed37_0 
  font-ttf-ubuntu    conda-forge/noarch::font-ttf-ubuntu-0.83-h77eed37_1 
  fontconfig         conda-forge/win-64::fontconfig-2.14.0-hce3cb01_0 
  fonts-conda-ecosy~ conda-forge/noarch::fonts-conda-ecosystem-1-0 
  fonts-conda-forge  conda-forge/noarch::fonts-conda-forge-1-0 
  freetype           conda-forge/win-64::freetype-2.12.1-hdaf720e_2 
  fribidi            conda-forge/win-64::fribidi-1.0.10-h8d14728_0 
  getopt-win32       conda-forge/win-64::getopt-win32-0.1-hcfcfb64_1 
  gettext            conda-forge/win-64::gettext-0.19.8.1-ha2e2712_1008 
  graphite2          conda-forge/win-64::graphite2-1.3.13-1000 
  graphviz           conda-forge/win-64::graphviz-6.0.1-h8f5d4a1_0 
  gts                conda-forge/win-64::gts-0.7.6-h7c369d9_2 
  harfbuzz           conda-forge/win-64::harfbuzz-5.2.0-h27de254_0 
  icu                conda-forge/win-64::icu-70.1-h0e60522_0 
  jpeg               conda-forge/win-64::jpeg-9e-hcfcfb64_3 
  lerc               conda-forge/win-64::lerc-4.0.0-h63175ca_0 
  libdeflate         conda-forge/win-64::libdeflate-1.14-hcfcfb64_0 
  libexpat           conda-forge/win-64::libexpat-2.5.0-h63175ca_1 
  libgd              conda-forge/win-64::libgd-2.3.3-h891f43f_3 
  libglib            conda-forge/win-64::libglib-2.72.1-h3be07f2_0 
  libpng             conda-forge/win-64::libpng-1.6.43-h19919ed_0 
  libsqlite          conda-forge/win-64::libsqlite-3.45.1-hcfcfb64_0 
  libtiff            conda-forge/win-64::libtiff-4.4.0-hc4f729c_5 
  libwebp            conda-forge/win-64::libwebp-1.3.2-hcfcfb64_1 
  libwebp-base       conda-forge/win-64::libwebp-base-1.3.2-hcfcfb64_0 
  libxcb             conda-forge/win-64::libxcb-1.15-hcd874cb_0 
  libzlib            conda-forge/win-64::libzlib-1.2.13-hcfcfb64_5 
  m2w64-gcc-libgfor~ conda-forge/win-64::m2w64-gcc-libgfortran-5.3.0-6 
  m2w64-gcc-libs     conda-forge/win-64::m2w64-gcc-libs-5.3.0-7 
  m2w64-gcc-libs-co~ conda-forge/win-64::m2w64-gcc-libs-core-5.3.0-7 
  m2w64-gmp          conda-forge/win-64::m2w64-gmp-6.1.0-2 
  m2w64-libwinpthre~ conda-forge/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2 
  msys2-conda-epoch  conda-forge/win-64::msys2-conda-epoch-20160418-1 
  pango              conda-forge/win-64::pango-1.50.10-hc1549de_0 
  pcre               conda-forge/win-64::pcre-8.45-h0e60522_0 
  pixman             conda-forge/win-64::pixman-0.43.4-h63175ca_0 
  pthread-stubs      conda-forge/win-64::pthread-stubs-0.4-hcd874cb_1001 
  python-graphviz    conda-forge/noarch::python-graphviz-0.20.1-pyh22cad53_0 
  python_abi         conda-forge/win-64::python_abi-3.12-4_cp312 
  ucrt               conda-forge/win-64::ucrt-10.0.22621.0-h57928b3_0 
  vc14_runtime       conda-forge/win-64::vc14_runtime-14.38.33130-h82b7239_18 
  xorg-kbproto       conda-forge/win-64::xorg-kbproto-1.0.7-hcd874cb_1002 
  xorg-libice        conda-forge/win-64::xorg-libice-1.1.1-hcd874cb_0 
  xorg-libsm         conda-forge/win-64::xorg-libsm-1.2.4-hcd874cb_0 
  xorg-libx11        conda-forge/win-64::xorg-libx11-1.8.7-hefa74cf_0 
  xorg-libxau        conda-forge/win-64::xorg-libxau-1.0.11-hcd874cb_0 
  xorg-libxdmcp      conda-forge/win-64::xorg-libxdmcp-1.1.3-hcd874cb_0 
  xorg-libxext       conda-forge/win-64::xorg-libxext-1.3.4-hcd874cb_2 
  xorg-libxpm        conda-forge/win-64::xorg-libxpm-3.5.17-hcd874cb_0 
  xorg-libxt         conda-forge/win-64::xorg-libxt-1.3.0-hcd874cb_1 
  xorg-xextproto     conda-forge/win-64::xorg-xextproto-7.3.0-hcd874cb_1003 
  xorg-xproto        conda-forge/win-64::xorg-xproto-7.0.31-hcd874cb_1007 

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2023.12.12~ --> conda-forge::ca-certificates-2024.2.2-h56e8100_0 
  openssl              pkgs/main::openssl-3.0.13-h2bbff1b_0 --> conda-forge::openssl-3.2.1-hcfcfb64_0 
  python                pkgs/main::python-3.12.1-h1d929f7_0 --> conda-forge::python-3.12.2-h2628c8c_0_cpython 
  tk                        pkgs/main::tk-8.6.12-h2bbff1b_0 --> conda-forge::tk-8.6.13-h5226925_1 
  vs2015_runtime     pkgs/main::vs2015_runtime-14.27.29016~ --> conda-forge::vs2015_runtime-14.38.33130-hcb4865c_18 
  zlib                    pkgs/main::zlib-1.2.13-h8cc25b3_0 --> conda-forge::zlib-1.2.13-hcfcfb64_5 

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi            pkgs/main/win-64::certifi-2024.2.2-py~ --> conda-forge/noarch::certifi-2024.2.2-pyhd8ed1ab_0 
  conda              pkgs/main::conda-24.1.2-py312haa95532~ --> conda-forge::conda-24.1.2-py312h2e8e312_0 

Downloading and Extracting Packages: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

Checking the latest supported CUDA version...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\tasha\TorchStudio\torchstudio\pythoninstall.py", line 33, in <module>
    import requests
  File "C:\Users\tasha\TorchStudio\python\Lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\tasha\TorchStudio\python\Lib\site-packages\urllib3\__init__.py", line 14, in <module>
    from ._base_connection import _TYPE_BODY
  File "C:\Users\tasha\TorchStudio\python\Lib\site-packages\urllib3\_base_connection.py", line 5, in <module>
    from .util.connection import _TYPE_SOCKET_OPTIONS
  File "C:\Users\tasha\TorchStudio\python\Lib\site-packages\urllib3\util\__init__.py", line 5, in <module>
    from .request import SKIP_HEADER, SKIPPABLE_HEADERS, make_headers
  File "C:\Users\tasha\TorchStudio\python\Lib\site-packages\urllib3\util\request.py", line 32, in <module>
    import zstandard as _unused_module_zstd  # type: ignore[import] # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tasha\TorchStudio\python\Lib\site-packages\zstandard\__init__.py", line 38, in <module>
    if platform.python_implementation() in ("CPython",):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tasha\TorchStudio\python\Lib\platform.py", line 1153, in python_implementation
    return _sys_version()[0]
           ^^^^^^^^^^^^^^
  File "C:\Users\tasha\TorchStudio\python\Lib\platform.py", line 1113, in _sys_version
    raise ValueError(
ValueError: failed to parse CPython sys.version: '3.12.1 | packaged by Anaconda, Inc. | (main, Jan 19 2024, 15:44:08) [MSC v.1916 64 bit (AMD64)]'
 
Error while installing packages

**Comment by gunkpunk** [comment]
FWIW, I have the same issue on macOS Ventura. (M1)

**Comment by Gilkovitch** [comment]
I try to install on macOS Monterey too, same issue ...

**Comment by davidsillou** [comment]
Same error on win11(with cuda support)

**Comment by jkingsec** [comment]
Same issue on Ubuntu 23.10

**Comment by Gilkovitch** [comment]
a bug for 4 users, 3 week ago not any answer ! great support !

**Comment by Gilkovitch** [comment]
> @Gilkovitch please understand this is a completely free program, I make zero revenue on it and so far I'm the only one maintaining it on my free time.
> 
> @Gilkovitch @gunkpunk @davidsillou @jkingsec @radsulcorp this should now be fixed in 0.9.17: https://github.com/TorchStudio/torchstudio/releases/tag/0.9.17

Sorry i don't know this

**Comment by radsulcorp** [comment]
Robin, thank you for fixing and closing out this issue (#60).

Alan
