### ISSUE TITLE
Unable to remote server :|

### ISSUE THREAD

**Issue by zaliir** [TorchStudio/torchstudio#63]
**Unable to connect server**
![could not update remote scripts](https://github.com/TorchStudio/torchstudio/assets/65438199/ad01eb02-fa35-4fd9-b8e9-4865fcfb0305)

![could not update remote scripts2](https://github.com/TorchStudio/torchstudio/assets/65438199/7baf7f91-33a5-4ba1-a788-e4368b0ac87b)

error message:
**Error: could not update remote scripts**

**Comment by divideconcept** [comment]
@zaliir this should now be fixed in 0.9.17: https://github.com/TorchStudio/torchstudio/releases/tag/0.9.17
