### ISSUE TITLE
Error during load dataset "celeb A"

### ISSUE THREAD

**Issue by zaliir** [TorchStudio/torchstudio#64]
error message:
File /home/ali/TorchStudio/python/lib/python3.12/site-packages/torchvision/datasets/utils.py, line 198, in download_file_from_google_drive
raise RuntimeError(
**RuntimeError: To download files from GDrive, 'gdown' is required. You can install it with 'pip install gdown'.**

![install gdown](https://github.com/TorchStudio/torchstudio/assets/65438199/f731481e-5cff-499e-894a-249a3487dccd)

After installing "gdown", it gives the same error again.

**Comment by divideconcept** [comment]
Then unfortunately it looks like it's an issue with PyTorch rather than TorchStudio...
